# Site settings
title: Nils Höhing
description: Vision-Language Models and Benchmarking
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
about: "Hi I am Nils and I work at the intersection. Apart from that I am a PhD student in spatial understanding for vision-language models at University College Dublin. Currently I am especially interested in benchmarks and evaluation."

# Social media links
social_links:
  - name: Twitter
    url: https://twitter.com/nilshoehing
  - name: GitHub
    url: https://github.com/nilshoehing

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 3
paginate_path: "/page/:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
